### ISSUE TITLE
Publish library to JCenter

### ISSUE THREAD

**Issue by bmuschko** [gradle/exemplar#41]
At the moment you have to define an additional repository just for this dependency.

```
repositories {
    jcenter()
    maven {
        url = uri("https://repo.gradle.org/gradle/libs")
    }
}
```

The dependency should be available in JCenter.

**Comment by britter** [comment]
With JCenter shutting down in Feb 2022, I don't think we're going to implement this. I recommend pulling this from the Gradle repository, but also setting content filters so that only examplar is looked up from there:

```kotlin
repositories {
    maven {
        url = uri("https://repo.gradle.org/gradle/libs")
        content {
            includeModule("org.gradle", "sample-check")
            includeModule("org.gradle", "sample-discovery")
        }
    }
    mavenCentral()
}
```
